package com.example.expensemanager;

import java.sql.Date;
import java.time.LocalDate;

public class Expense {
    private int id;
    private String title;
    private LocalDate expenseDate; // Use LocalDate for easier handling in Java
    private double amount;
    private String unit;

    // Constructor for creating new expenses (ID is auto-generated by DB)
    public Expense(String title, LocalDate expenseDate, double amount, String unit) {
        this.title = title;
        this.expenseDate = expenseDate;
        this.amount = amount;
        this.unit = unit;
    }

    // Constructor for expenses retrieved from DB (includes ID)
    public Expense(int id, String title, LocalDate expenseDate, double amount, String unit) {
        this.id = id;
        this.title = title;
        this.expenseDate = expenseDate;
        this.amount = amount;
        this.unit = unit;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public LocalDate getExpenseDate() {
        return expenseDate;
    }

    // Setter for ID (useful when retrieving from DB)
    public void setId(int id) {
        this.id = id;
    }

    public double getAmount() {
        return amount;
    }

    public String getUnit() {
        return unit;
    }

    // Setters
    public void setTitle(String title) {
        this.title = title;
    }

    public void setExpenseDate(LocalDate expenseDate) {
        this.expenseDate = expenseDate;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    // For converting LocalDate to java.sql.Date for database operations
    public java.sql.Date getExpenseSqlDate() {
        return Date.valueOf(this.expenseDate);
    }

    @Override
    public String toString() {
        return "Expense{" +
               "id=" + id +
               ", title='" + title + '\'' +
               ", expenseDate=" + expenseDate +
               ", amount=" + amount +
               ", unit='" + unit + '\'' +
               '}';
    }
}
